import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {  ClerkProvider } from '@clerk/nextjs'


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "buyer's Leads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={inter.className}
          >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
